before_script:
  - apk add bash
  - app-get install git
  - apk add python3
  - bash -l -c "git clone -b master git@gitlab.computervoice.com:cvs/cpp_ci_utils.git"
#Stages
stages:
  - build
  - tests
#Variables
variables:
  dir_build : "build"
  linux_docker_image: "centos_gcc_legacy:1.8.0"
  production_generic_set: "production_gcc_generic_v2"
build_job:
  stage: build
  tags:
    - linux
    - docker
  only:
    - devel
    - master
    - web
    - /^.*_.*$/
  script:
    - echo "build_project"
    - python ../cpp_ci_utils/cli.py build --flags $production_gcc_generic_v2 -bm yes -scl yes
  artifacts:
    paths:
     - $dir_build/project
     - $dir_build/project_test
     - $dir_build/build.out
    expire_in : 7 day
run_tests_job:
  stage: tests
  image: $linux_docker_image
  tags: 
    - linux
    - docker
  only:
    - web
    - devel
    - master
    - /^.*_.*$/
  script:
    - echo "unittest"
    - python ../cpp_ci_utils/cli.py run unittest $dir_build/project_test
  dependencies:
    - build_job

run_check_warnings_job:
  stage: tests
  image: $linux_docker_image
  tags: 
    - linux
    - docker
  only:
    - web
    - devel
    - master
    - /^.*_.*$/
  script:
    - echo "check_warnings"
    - python ../cpp_ci_utils/cli.py check_warnings -clf $dir_build/build.out -mw 1
  dependencies:
    - build_job
    