before_script:
  - echo "Run before Job"
  - bash -l -c "git clone -b master git@gitlab.computervoice.com:cvs/cpp_ci_utils.git"
#Stages
stages:
  - build
  - tests
#Variables
variables:
  dir_build : "build"
  linux_docker_image: "centos_gcc_legacy_generic_v3"
  production_generic_set: "production_gcc_generic_v2"

build_job:
  stage: build
  tags:
    - linux
    - docker
  only:
    - devel
    - master
    - web
    - /^.*_.*$/
  script:
    - cd build
    - conan install ..
    - conan build ..
    #- > 
      #bash -l ci/ci.sh --project 
  artifacts:
    paths:
     - build/project
    expire_in : 7 day

run_tests_job:
  stage: tests
  image: $linux_docker_image
  tags: 
    - linux
    - docker
  only:
    - web
    - devel
    - master
    - /^.*_.*$/
  script:
    echo "Should be test"
  dependencies:
    - build_job
    