before_script:
  - echo "Run before Job"
  - bash -l -c "git clone -b master git@gitlab.computervoice.com:cvs/cpp_ci_utils.git"
#Stages
stages:
  - build
  - tests
#Variables
variables:
  dir_build : "build"
  linux_docker_image: "centos_gcc_legacy_generic_v3"
  production_generic_set: "production_gcc_generic_v2"

build_centos:
  stage: build
  tags:
    - linux
    - docker
  only:
    - devel
    - web
    - /^.*_.*$/
  script:
    - > 
      bash -l ci/ci.sh --project 
  artifacts:
    paths:
     - build/project
    expire_in : 7 day

run_tests:
  stage: tests
  image: $linux_docker_image
  tags: 
    - linux
    - docker
  only:
    - web
    - devel
    - /^.*_.*$/
  script:
    bash -l ci/ci.bat --run_unit_tests projet_test"
  dependencies:
    - build_centos
  artifacts:
    paths:
      - build/project_test
    expire_in : 7 day
  