before_script:
  - echo "Run before Job"
  - bash -l -c "git clone -b master git@gitlab.computervoice.com:cvs/cpp_ci_utils.git"
#Stages
stages:
  - build
  - tests
#Variables
variables:
  dir_build : "build"
  linux_docker_image: "centos_gcc_legacy_generic_v3"
  production_generic_set: "production_gcc_generic_v2"
build_job:
  stage: build
  tags:
    - linux
    - docker
  only:
    - devel
    - master
    - web
    - /^.*_.*$/
  script:
    - python ../cpp_ci_utils/cli.py build --flags production_gcc_generic_v2 -bm yes -scl yes
  artifacts:
    paths:
     - project
     - project_test
     - build.out
    expire_in : 7 day

run_tests_job:
  stage: tests
  image: $linux_docker_image
  tags: 
    - linux
    - docker
  only:
    - web
    - devel
    - master
    - /^.*_.*$/
  script:
    - python ../cpp_ci_utils/cli.py run unittest ./build/project_test
  dependencies:
    - build_job

run_check_warnings_job:
  stage: tests
  image: $linux_docker_image
  tags: 
    - linux
    - docker
  only:
    - web
    - devel
    - master
    - /^.*_.*$/
  script:
    - python ../cpp_ci_utils/cli.py check_warnings -clf ./build/build.out -mw 1
  dependencies:
    - build_job
    